[build]
  publish = "."
  command = "npm run build"

[[redirects]]
  from = "/api/*"
  to = "https://abhirup-glich.github.io/test-2-backend-/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/auth/*"
  to = "https://abhirup-glich.github.io/test-2-backend-/auth/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/user/*"
  to = "https://abhirup-glich.github.io/test-2-backend-/user/:splat"
  status = 200
  force = true
